'''empty message

Revision ID: 474002a798c6
Revises: 57185524ffc9
Create Date: 2023-12-11 03:41:13.978370

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474002a798c6'
down_revision = '57185524ffc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('REFRESH', 'ACCESS', name='jwttype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name=op.f('uq_jwt_jti'))
    )
    with op.batch_alter_table('jwt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwt_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('verified')
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('jwt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwt_user_id'))

    op.drop_table('jwt')
    sa.Enum('REFRESH', 'ACCESS', name='jwttype').drop(op.get_bind())
    # ### end Alembic commands ###
