"""
Initial migration

Revision ID: 57185524ffc9
Revises: 
Create Date: 2023-11-25 05:02:32.296430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57185524ffc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False, unique=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
