'''empty message

Revision ID: b0ef03384ad6
Revises: 474002a798c6
Create Date: 2024-02-06 05:21:13.690194

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0ef03384ad6'
down_revision = '474002a798c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description', name=op.f('uq_trip_description')),
    sa.UniqueConstraint('name', name=op.f('uq_trip_name'))
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_user_id'))

    op.drop_table('trip')
    # ### end Alembic commands ###
