#!/bin/bash

DATA_PATH=$(dirname $(realpath -s $0))/osrm_data


remove_containers() {
    docker stop osrm-extract osrm-partition osrm-customize osrm-server &> /dev/null || true
    docker rm osrm-extract osrm-partition osrm-customize osrm-server &> /dev/null || true
}


generate() {
    if ! [ -d "$DATA_PATH" ]; then
        filename="${1-http://download.geofabrik.de/north-america/us/ohio-latest.osm.pbf}"
        target_file=${2-ohio-latest}
        echo "Purging ${DATA_PATH}"
        rm -rf "$DATA_PATH"
            
        # re-generate input data for the service
        wget -P $DATA_PATH $filename
        
        if [ $? -eq 0 ]; then
            remove_containers
            docker run --name osrm-extract -t -v "${DATA_PATH}:/data" ghcr.io/project-osrm/osrm-backend osrm-extract -p /opt/car.lua "/data/${target_file}.osm.pbf"
            docker run --name osrm-partition -t -v "${DATA_PATH}:/data" ghcr.io/project-osrm/osrm-backend osrm-partition "/data/${target_file}.osrm"
            docker run --name osrm-customize -t -v "${DATA_PATH}:/data" ghcr.io/project-osrm/osrm-backend osrm-customize "/data/${target_file}.osrm"
            remove_containers
        fi
    fi
}

generate $1 $2