#!/bin/bash

FILE_PATH=$(dirname $(realpath -s $0))
YML_FILE="${FILE_PATH}/compose.ci.yaml"

cleanup() {
    docker compose -f "$YML_FILE" down
    exit 1
}

trap cleanup SIGINT SIGKILL

rebuild() {
    docker compose -f "$YML_FILE" build
}

run_tests() {
    docker compose -f "$YML_FILE" up --abort-on-container-exit
    test_status=$?
    docker compose -f "$YML_FILE" down
    exit $test_status
}

help()
{
   # Display Help
   echo "Runs Optimize The Drive tests."
   echo
   echo "Syntax: tests [OPTION]..."
   echo "OPTIONS:"
   echo "-h, --help       Show this help message." 
   echo "-b, --build     (Re)build the test images."
   echo "-r, --run        Run the tests."
}

options=$(getopt -o hbr -l help,build,run -n "$0" -- "$@") || exit
eval set -- "$options"

# Parse short options
# while getopts "hgsea" option; do
while [[ $1 != -- ]]; do
   case $1 in
        -h|--help) # display Help
            help
            shift 1
            ;;
        -b|--build) # Build tests
            rebuild
            shift 1
            ;;
        -r|--run) # Run tests
            run_tests
            shift 1
            ;;
        *) echo "bad option: $1" >&2; exit 1;;
   esac
done

