FROM python:3

RUN apt-get update
RUN apt-get install -y netcat-traditional

# Create app directory
WORKDIR /app

# Install app dependencies
COPY requirements.txt /app
COPY requirements.test.txt /app

RUN pip install -r requirements.txt -r requirements.test.txt

# Bundle app source
COPY . /app
